package modele;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public enum Pays {
	AF("Afghanistan"),
    AL("Albanie"),
    DZ("Algerie"),
    AD("Andorre"),
    AO("Angola"),
    AG("Antigua et Barbuda"),
    SA("Arabie saoudite"),
    AR("Argentine"),
    AM("Armenie"),
    AU("Australie"),
    AT("Autriche"),
    AZ("Azerbaidjan"),
    BS("Bahamas"),
    BH("Bahrein"),
    BD("Bangladesh"),
    BB("Barbade"),
    BY("Belarus"),
    BE("Belgique"),
    BZ("Belize"),
    BJ("Benin"),
    BT("Bhoutan"),
    BO("Bolivie"),
    BA("Bosnie Herzegovine"),
    BW("Botswana"),
    BR("Bresil"),
    BN("Brunei"),
    BG("Bulgarie"),
    BF("Burkina Faso"),
    BI("Burundi"),
    KH("Cambodge"),
    CM("Cameroun"),
    CA("Canada"),
    CV("Cap Vert"),
    CF("Republique centrafricaine"),
    CL("Chili"),
    CN("Chine"),
    CY("Chypre"),
    CO("Colombie"),
    KM("Comores"),
    CG("Congo"),
    KP("Coree du Nord"),
    KR("Coree du Sud"),
    CR("Costa Rica"),
    CI("Cote d'Ivoire"),
    HR("Croatie"),
    CU("Cuba"),
    DK("Danemark"),
    DJ("Djibouti"),
    DM("Dominique"),
    EG("Egypte"),
    AE("Emirats Arabes Unis"),
    EC("Equateur"),
    ER("Erythree"),
    ES("Espagne"),
    EE("Estonie"),
    SZ("Eswatini"),
    US("Etats Unis"),
    ET("Ethiopie"),
    FJ("Fidji"),
    FI("Finlande"),
    FR("France"),
    GA("Gabon"),
    GM("Gambie"),
    GE("Georgie"),
    GH("Ghana"),
    GR("Grece"),
    GD("Grenade"),
    GT("Guatemala"),
    GN("Guinee"),
    GW("Guinee Bissau"),
    GQ("Guinee equatoriale"),
    GY("Guyana"),
    HT("Haiti"),
    HN("Honduras"),
    HU("Hongrie"),
    CK("Iles Cook"),
    MH("Iles Marshall"),
    SB("Iles Salomon"),
    IN("Inde"),
    ID("Indonesie"),
    IQ("Irak"),
    IR("Iran"),
    IE("Irlande"),
    IS("Islande"),
    IL("Israel"),
    IT("Italie"),
    JM("Jamaique"),
    JP("Japon"),
    JO("Jordanie"),
    KZ("Kazakhstan"),
    KE("Kenya"),
    KG("Kirghizistan"),
    KI("Kiribati"),
    KW("Koweit"),
    LA("Laos"),
    LS("Lesotho"),
    LV("Lettonie"),
    LB("Liban"),
    LR("Liberia"),
    LY("Libye"),
    LI("Liechtenstein"),
    LT("Lituanie"),
    LU("Luxembourg"),
    MK("Macedoine"),
    MG("Madagascar"),
    MY("Malaisie"),
    MW("Malawi"),
    MV("Maldives"),
    ML("Mali"),
    MT("Malte"),
    MA("Maroc"),
    MU("Maurice"),
    MR("Mauritanie"),
    MX("Mexique"),
    FM("Micronesie"),
    MD("Moldavie"),
    MC("Monaco"),
    MN("Mongolie"),
    ME("Montenegro"),
    MZ("Mozambique"),
    NA("Namibie"),
    NR("Nauru"),
    NP("Nepal"),
    NI("Nicaragua"),
    NE("Niger"),
    NG("Nigeria"),
    NU("Niue"),
    NO("Norvege"),
    NZ("Nouvelle Zelande"),
    OM("Oman"),
    UG("Ouganda"),
    UZ("Ouzbekistan"),
    PK("Pakistan"),
    PW("Palaos"),
    PS("Palestine"),
    PA("Panama"),
    PG("Papua New Guinea"),
    PY("Paraguay"),
    NL("Pays Bas"),
    PE("Perou"),
    PH("Philippines"),
    PL("Pologne"),
    PT("Portugal"),
    QA("Qatar"),
    DO("Republique dominicaine"),
    CZ("Republique tcheque"),
    RO("Roumanie"),
    GB("Royaume Uni"),
    RU("Russie"),
    RW("Rwanda"),
    KN("Saint Christophe et Nevis"),
    LC("Sainte Lucie"),
    SM("Saint Marin"),
    SV("Salvador"),
    WS("Samoa"),
    ST("Sao Tome et Principe"),
    SN("Senegal"),
    RS("Serbie"),
    SC("Seychelles"),
    SL("Sierra Leone"),
    SG("Singapour"),
    SK("Slovaquie"),
    SI("Slovenie"),
    SO("Somalie"),
    SD("Soudan"),
    SS("Soudan du Sud"),
    LK("Sri Lanka"),
    SE("Suede"),
    CH("Suisse"),
    SR("Suriname"),
    SY("Syrie"),
    TJ("Tadjikistan"),
    TW("Taiwan"),
    TZ("Tanzanie"),
    TD("Tchad"),
    TH("Thailande"),
    TL("Timor Oriental"),
    TG("Togo"),
    TO("Tonga"),
    TT("Trinite et Tobago"),
    TN("Tunisie"),
    TM("Turkmenistan"),
    TR("Turquie"),
    TV("Tuvalu"),
    UA("Ukraine"),
    UY("Uruguay"),
    VU("Vanuatu"),
    VA("Vatican"),
    VE("Venezuela"),
    VN("Vietnam"),
    YE("Yemen"),
    ZM("Zambie"),
    ZW("Zimbabwe");

    private final String denomination;

    private Pays(String denomination) {
        this.denomination = denomination;
    }

    public String denomination() {
        return denomination;
    }
    
    public static Pays getPays(String nom) {
    	for (Pays pays : Pays.values()) {
    		if (pays.denomination().equals(nom)) {
    			return pays;
    		}
    	}
    	return null;
    }
}
